(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Richard Luo, created 2008-11-06."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "#1a1a1a")
      (foreground-color . "#1a1a1a")
      (mouse-color . "#1a1a1a"))
     ((browse-kill-ring-separator-face . bold)
      (cscope-use-face . t)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (rmail-highlight-face . rmail-highlight)
      (term-default-bg-color . "#ffffff")
      (term-default-fg-color . "#1a1a1a")
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:bold t :stipple nil :background "#ffffff" :foreground "#1a1a1a" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 101 :width normal :family "misc-fixed"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:foreground "DarkGoldenrod"))))
     (change-log-date ((t (:foreground "RosyBrown"))))
     (change-log-email ((t (:foreground "DarkGoldenrod"))))
     (change-log-file ((t (:foreground "Blue1"))))
     (change-log-function ((t (:foreground "DarkGoldenrod"))))
     (change-log-list ((t (:foreground "Purple"))))
     (change-log-name ((t (:foreground "CadetBlue"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (completions-common-part ((t (:bold t :family "misc-fixed" :width normal :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#1a1a1a" :background "#ffffff" :stipple nil :height 101))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "black"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "#1a1a1a"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey85"))))
     (diff-header ((t (:background "grey85"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-index ((t (:bold t :weight bold :background "grey70"))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey70"))))
     (diff-refine-change ((t (:background "grey90"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "Blue1"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "CadetBlue"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-symlink ((t (:foreground "Purple"))))
     (dired-warn-writable ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-warning ((t (:bold t :weight bold :foreground "Red1"))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-product ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly ((t (:foreground "Brown"))))
     (eshell-ls-special ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink ((t (:bold t :foreground "Dark Cyan" :weight bold))))
     (eshell-ls-unreadable ((t (:foreground "Grey30"))))
     (eshell-prompt ((t (:bold t :foreground "Red" :weight bold))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "Orchid"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (font-lock-doc-face ((t (:foreground "RosyBrown"))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Orchid"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "RosyBrown"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (fvwm-rgb-value-face ((t (:foreground "LightSalmon"))))
     (fvwm-special-face ((t (:foreground "SteelBlue"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-indicator-face ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "#000000" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (:background "#1a1a1a"))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "lightgoldenrod2"))))
     (scroll-bar ((t (:background "grey75" :foreground "#000000"))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (svn-status-blame-highlight-face ((t (:background "darkseagreen2"))))
     (svn-status-blame-rev-number-face ((t (:foreground "DarkGoldenrod"))))
     (svn-status-directory-face ((t (:foreground "blue4"))))
     (svn-status-filename-face ((t (:foreground "chocolate"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "green3"))))
     (svn-status-marked-popup-face ((t (:foreground "green3"))))
     (svn-status-switched-face ((t (:foreground "CadetBlue"))))
     (svn-status-symlink-face ((t (:foreground "cornflower blue"))))
     (svn-status-update-available-face ((t (:foreground "magenta"))))
     (template-message-face ((t (:bold t :weight bold))))
     (tool-bar ((t (:background "#edeceb" :foreground "#000000" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
